/*Actualiza el campo certificado a YES en CEGID*/

UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '43514' AND ARKTCOMART = 'B'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '43607' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '42805' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '17309' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '44043' AND ARKTCOMART = ''
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '15809' AND ARKTCOMART = 'B'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '43513' AND ARKTCOMART = 'B'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '43656' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '44003' AND ARKTCOMART = ''
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '31781' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '37533' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '30707' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '33116' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '33117' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '34256' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '33148' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '15813' AND ARKTCOMART = 'D'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '35700' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '37549' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '15849' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '34224' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '36124' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '35115' AND ARKTCOMART = 'B'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '35187' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '42804' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '36050' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '17273' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '42809' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '33750' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '17734' AND ARKTCOMART = 'D'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '34245' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '36091' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '36098' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '34920' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '35045' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '31204' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '40227' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '57902' AND ARKTCOMART = ''
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '40508' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '35089' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '43624' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '31784' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '35162' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '33026' AND ARKTCOMART = 'B'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '38107' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '44004' AND ARKTCOMART = ''
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '38111' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '15812' AND ARKTCOMART = 'D'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '44010' AND ARKTCOMART = ''
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '15814' AND ARKTCOMART = 'D'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '35231' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '15815' AND ARKTCOMART = 'D'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '15816' AND ARKTCOMART = 'D'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '44011' AND ARKTCOMART = ''
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '15817' AND ARKTCOMART = 'D'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '15821' AND ARKTCOMART = 'C'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '15822' AND ARKTCOMART = 'C'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '15823' AND ARKTCOMART = 'B'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '33095' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '15826' AND ARKTCOMART = 'C'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '15834' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '15835' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '15843' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '15845' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '15848' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '38126' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '44033' AND ARKTCOMART = ''
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '15850' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '15851' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '44035' AND ARKTCOMART = ''
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '15855' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '42308' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '44050' AND ARKTCOMART = ''
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '15874' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '15875' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '36027' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '15886' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '33209' AND ARKTCOMART = 'B'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '44201' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '44203' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '44204' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '44205' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '44209' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '44210' AND ARKTCOMART = ''
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '35192' AND ARKTCOMART = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '44023' AND ARKTCOMART = ''
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE ARKTCODART = '44044' AND ARKTCOMART = ''


--//////////////////////////////////////////////////////////////////
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '43514' --AND RTRIM(ARKTCOMART) = 'B'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '43607' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '42805' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '17309' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '44043' --AND RTRIM(ARKTCOMART) = ''
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '15809' --AND RTRIM(ARKTCOMART) = 'B'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '43513' --AND RTRIM(ARKTCOMART) = 'B'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '43656' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '44003' --AND RTRIM(ARKTCOMART) = ''
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '31781' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '37533' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '30707' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '33116' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '33117' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '34256' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '33148' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '15813' --AND RTRIM(ARKTCOMART) = 'D'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '35700' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '37549' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '15849' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '34224' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '36124' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '35115' --AND RTRIM(ARKTCOMART) = 'B'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '35187' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '42804' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '36050' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '17273' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '42809' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '33750' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '17734' --AND RTRIM(ARKTCOMART) = 'D'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '34245' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '36091' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '36098' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '34920' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '35045' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '31204' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '40227' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '57902' --AND RTRIM(ARKTCOMART) = ''
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '40508' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '35089' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '43624' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '31784' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '35162' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '33026' --AND RTRIM(ARKTCOMART) = 'B'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '38107' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '44004' --AND RTRIM(ARKTCOMART) = ''
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '38111' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '15812' --AND RTRIM(ARKTCOMART) = 'D'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '44010' --AND RTRIM(ARKTCOMART) = ''
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '15814' --AND RTRIM(ARKTCOMART) = 'D'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '35231' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '15815' --AND RTRIM(ARKTCOMART) = 'D'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '15816' --AND RTRIM(ARKTCOMART) = 'D'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '44011' --AND RTRIM(ARKTCOMART) = ''
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '15817' --AND RTRIM(ARKTCOMART) = 'D'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '15821' --AND RTRIM(ARKTCOMART) = 'C'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '15822' --AND RTRIM(ARKTCOMART) = 'C'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '15823' --AND RTRIM(ARKTCOMART) = 'B'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '33095' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '15826' --AND RTRIM(ARKTCOMART) = 'C'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '15834' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '15835' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '15843' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '15845' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '15848' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '38126' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '44033' --AND RTRIM(ARKTCOMART) = ''
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '15850' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '15851' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '44035' --AND RTRIM(ARKTCOMART) = ''
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '15855' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '42308' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '44050' --AND RTRIM(ARKTCOMART) = ''
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '15874' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '15875' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '36027' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '15886' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '33209' --AND RTRIM(ARKTCOMART) = 'B'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '44201' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '44203' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '44204' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '44205' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '44209' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '44210' --AND RTRIM(ARKTCOMART) = ''
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '35192' --AND RTRIM(ARKTCOMART) = 'A'
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '44023' --AND RTRIM(ARKTCOMART) = ''
UPDATE [PMI].[dbo].[UARTICLE] SET ARKTCERTIF = 'YES' WHERE RTRIM(ARKTCODART) = '44044' --AND RTRIM(ARKTCOMART) = ''

SELECT * FROM [PMI].[dbo].[UARTICLE] WHERE RTRIM(ARKTCODART) IN ('43514',
'43607',
'42805',
'17309',
'44043',
'15809',
'43513',
'43656',
'44003',
'31781',
'37533',
'30707',
'33116',
'33117',
'34256',
'33148',
'15813',
'35700',
'37549',
'15849',
'34224',
'36124',
'35115',
'35187',
'42804',
'36050',
'17273',
'42809',
'33750',
'17734',
'34245',
'36091',
'36098',
'34920',
'35045',
'31204',
'40227',
'57902',
'40508',
'35089',
'43624',
'31784',
'35162',
'33026',
'38107',
'44004',
'38111',
'15812',
'44010',
'15814',
'35231',
'15815',
'15816',
'44011',
'15817',
'15821',
'15822',
'15823',
'33095',
'15826',
'15834',
'15835',
'15843',
'15845',
'15848',
'38126',
'44033',
'15850',
'15851',
'44035',
'15855',
'42308',
'44050',
'15874',
'15875',
'36027',
'15886',
'33209',
'44201',
'44203',
'44204',
'44205',
'44209',
'44210',
'35192',
'44023',
'44044')