name: Commit and Push

on:
  push:
    branches:
      - main  # Puedes cambiar esto al nombre de tu rama principal si es diferente

jobs:
  commit_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Asegúrate de haber configurado esta clave SSH como un secreto en la configuración del repositorio

    - name: Configure git
      run: |
        git config user.name "Raptor057"
        git config user.email "rogelioarriaga@live.com.mx"

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Automatic commit from GitHub Actions"
        git push git@github.com:Raptor057/SQL.git HEAD:main
