SELECT TOP (1000) [id]
      ,[id_line]
      ,[is_stoped]
      ,[is_running]
      ,[is_finished]
      ,[order]
      ,[line]
      ,[subindex]
      ,[codew]
      ,[part_number]
      ,[rev]
      ,[part_desc]
      ,[weight_unit]
      ,[ratio]
      ,[std_pack]
      ,[ref_ext]
      ,[client_code]
      ,[client_name]
      ,[current_qty]
      ,[target_qty]
      ,[start_date]
      ,[end_date]
      ,[created_by]
      ,[end_by]
      ,[end_at]
      ,[dblid]
      ,[last_update_time]
  FROM [APPS].[dbo].[pro_production] WHERE part_number = '85409'
  AND 
  start_date >= '2023-12-20 13:00:21.520' AND end_at <= '2023-12-20 18:49:04.177'
  order by id asc