SELECT [Id]
      ,[fecha]
      ,[Hora]
      , CONVERT(DATETIME, [fecha] + ' ' + [Hora], 113) AS [LocalDateTime]
      ,[qty]
      ,RIGHT([line],2) AS [LineCode]
      ,[line]
      ,[FAMILIA]
      ,[modelo]
      ,[part_num]
      ,[rev]
      ,[description]
      ,[codew]
      ,[customer]
      ,[cust_pn]
      ,[po_num]
      ,[LOTES]
      ,[master_type]
      ,[juliano]
      ,[was_partial]
      ,[is_partial]
      ,[Closed]
      ,[aprov]
      ,[aprov_user]
      ,[aprov_date]
      ,[aprov_ID]
      ,[shipped]
      ,[ship_user]
      ,[ship_date]
      ,[reworked]
      ,[reworked_ok]
      ,[ateq_val]
      ,[Reject_comments]
      ,[Reported_unaprov]
      ,[Shipped_wh]
      ,[ship_user_WH]
      ,[ship_date_WH]
      ,[is_active]
      ,[comments]
      ,[blocked]
      ,[date_blocked]
      ,[RMNC]
      ,[date_released]
  FROM [TRAZAB].[dbo].[Master_labels_WB]
--   WHERE CONVERT(DATETIME, [fecha] + ' ' + [Hora], 113) 
--   > GETDATE()-(SELECT DATEDIFF(day, CAST(YEAR(GETDATE()) AS VARCHAR) + '-01-01', DATEADD(year, 1, CAST(YEAR(GETDATE()) AS VARCHAR) + '-01-01'))) -- This line returns the current date minus the total number of days in the current year, in summary the current date minus 365 or 366 days.
  ORDER BY Id ASC