SELECT top 1000 * from NOMENC
WHERE NOKTCODPF = '32093'

SELECT top 100 * from Z_MEMOIREPLC_API 

SELECT top 100 * from ZARTICLE_API WHERE Code_BT = 'W8681227'

SELECT top 1000 * FROM PARCG WHERE PZKTPARC = 'O47498'

SELECT top 1 * FROM [PMI].[dbo].[PARCG] PAG INNER JOIN NOMENC NOM ON NOM.NOCTCODECP = PAG.PZCTCODART WHERE NOM.NOKTCODPF = '37314' --AND NOM.NOKTCOMPF = @ProdLine