SELECT U.ARKTPATENT, A.*
FROM [PMI].[dbo].[ARTICLE] A
INNER JOIN [PMI].[dbo].[UARTICLE] U ON A.ARKTSOC = U.ARKTSOC AND A.ARKTCODART = U.ARKTCODART
WHERE A.ARKTSOC = 300
  AND A.ARCTSECART = '0081'
  --AND LEN(LTRIM(RTRIM(U.ARKTPATENT))) > 0


  SELECT U.ARKTPATENT
  FROM [PMI].[dbo].[ARTICLE] A
INNER JOIN [PMI].[dbo].[UARTICLE] U ON A.ARKTSOC = U.ARKTSOC AND A.ARKTCODART = U.ARKTCODART
WHERE A.ARKTSOC = 300
  AND A.ARCTSECART = '0081'
  AND LEN(LTRIM(RTRIM(U.ARKTPATENT))) > 0
GROUP BY U.ARKTPATENT;
