SELECT top 100 
ZMA.CODE_MACHINE,
ZMA.MACHINE_NAME,
ZMA.CODART,
--ZMA.COMART,
ZMA.Code_BT,
ZMA.CODE_ETI,
NOM.NOCTCODECP,
ZA.QTE_DEMANDEE,
ZA.QTE_REALISEE
FROM UARTICLE UA  
INNER JOIN ARTICLE ART
ON UA.ARKTCODART= ART.ARKTCODART
INNER JOIN NOMENC NOM
ON NOM.NOKTCODPF=ART.ARKTCODART AND NOM.NOCTLIBCOM like '%MOLD%'
INNER JOIN z_memoireplc_api ZMA
ON ZMA.CODART COLLATE French_CS_AS_KS_WS = Art.ARKTCODART
INNER JOIN [PMI].[dbo].[ZARTICLE_API] ZA
ON ZA.Code_BT=ZMA.Code_BT
GROUP BY ZMA.CODE_MACHINE,
ZMA.MACHINE_NAME,
ZMA.CODART,
--ZMA.COMART,
ZMA.Code_BT,
ZMA.CODE_ETI,
NOM.NOCTCODECP,
ZA.QTE_DEMANDEE,
ZA.QTE_REALISEE

--SELECT * FROM z_memoireplc_api ZMA
--SELECT * FROM [PMI].[dbo].[ZARTICLE_API] ZA

