SELECT [Telesis_no]
      ,[Linea]
      ,[no_empleado]
      ,[fecha_scan]
      ,[hora_scan]
      ,[ETI_no]
      ,[component_number]
      ,[ETI_001]
      ,[Modelo]
      ,[NP_FINAL]
      ,[CMP_REV]
      ,[ETI_status]
      ,[type_testing]
  FROM [TRAZAB].[dbo].[Trazab_Rider] WHERE fecha_scan = '31-Jan-2023' AND Telesis_no in (SELECT [TM_id]  FROM [TRAZAB].[dbo].[Master_lbl_TMid] WHERE Master_id in (SELECT [Id] FROM [TRAZAB].[dbo].[Master_labels_WB] where  fecha = '31-Jan-2023' AND [line] = 'RIDER LE'))