-- SELECT DISTINCT T1.NOCTCODECP AS [Numero de Componente], T1.NOCTCOMCPT AS [Rev], T1.NOCNQTECOM AS [Cantidad], T2.ARCTCODFAM AS [Familia], T2.ARITNATURE AS [Cap Tunel], T3.ARKCRITPAR AS [???], T3.APKSTDPACK AS [???]
-- FROM NOMENC T1
-- RIGHT JOIN UARTICLE T3 ON T1.NOCTCODECP = T3.ARKTCODART AND T1.NOCTCOMCPT = T3.ARKTCOMART
-- LEFT JOIN ARTICLE T2 ON T1.NOCTCODECP = T2.ARKTCODART AND (T1.NOCTCOMCPT = T2.ARCTCODPLA OR T1.NOCTCOMCPT = T2.ARKTCOMART)
-- WHERE T2.ARCTCODFAM IN ('CMP', 'PMQ', 'PM', 'DIV') AND T1.NOKTCODPF = '87245' AND T1.NOKTCOMPF = 'LE' AND T2.ARCTFATN <> 17


SELECT DISTINCT T1.NOCTCODECP AS [N_Componente], T1.NOCTCOMCPT AS [Rev], T1.NOCTCODOPE AS [Tunel]
FROM MXSRVCEGID.PMI.dbo.NOMENC T1
RIGHT JOIN UARTICLE T3 ON T1.NOCTCODECP = T3.ARKTCODART AND T1.NOCTCOMCPT = T3.ARKTCOMART
LEFT JOIN ARTICLE T2 ON T1.NOCTCODECP = T2.ARKTCODART AND (T1.NOCTCOMCPT = T2.ARCTCODPLA OR T1.NOCTCOMCPT = T2.ARKTCOMART)
WHERE 
--T2.ARCTCODFAM IN ('CMP', 'PMQ', 'PM', 'DIV') 
T2.ARITNATURE<>4
AND T1.NOKTCODPF = '87245' AND T1.NOKTCOMPF = 'LE' AND T2.ARCTFATN <> 17
Order BY Tunel ASC
