SELECT COUNT([NOKTCODPF]) AS [COUNT Boom] FROM [TRAZAB].[cegid].[bom] WHERE NOKTCODPF = '85540' AND NOKTCOMPF = 'LH'

  --delete cegid.bom WHERE NOKTCODPF = '85540' AND NOKTCOMPF = 'LH'

 -- SELECT CASE WHEN (SELECT COUNT([NOKTCODPF]) AS [COUNT Boom] FROM [TRAZAB].[cegid].[bom] WHERE NOKTCODPF = '85540' AND NOKTCOMPF = 'LH') > 0 THEN 1 ELSE 0 END AS Result