/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [id]
      ,[id_line]
      ,[is_stoped]
      ,[is_running]
      ,[is_finished]
      ,[order]
      ,[line]
      ,[subindex]
      ,[codew]
      ,[part_number]
      ,[rev]
      ,[part_desc]
      ,[weight_unit]
      ,[ratio]
      ,[std_pack]
      ,[ref_ext]
      ,[client_code]
      ,[client_name]
      ,[current_qty]
      ,[target_qty]
      ,[start_date]
      ,[end_date]
      ,[created_by]
      ,[end_by]
      ,[end_at]
      ,[dblid]
      ,[last_update_time]
  FROM [APPS].[dbo].[pro_production]
  where part_number='85746'