USE PMI;
GO

DECLARE
    @part_no NVARCHAR(50) = '85621-REAR',
    @line_code NVARCHAR(50) = 'LQ';

DECLARE
    @GTMEX INT = 300,
    @EMPTY_STRING NVARCHAR(50) = '' ,
    @COMPRADO NVARCHAR(50) = 'CMP',
    @MAQUINADO NVARCHAR(50) = 'PMQ',
    @MOLDEADO NVARCHAR(50) = 'PM',
    @DIVERSOS NVARCHAR(50) = 'DIV',
    @ACE NVARCHAR(50) = 'ACE';

DECLARE @FAMILIAS TABLE(CODE NVARCHAR(50) COLLATE French_CS_AS_KS_WS);
INSERT INTO @FAMILIAS VALUES(@COMPRADO),(@MAQUINADO),(@MOLDEADO),(@DIVERSOS),(@ACE);

SELECT DISTINCT T1.NOCTCODECP, T1.NOCTCOMCPT, T1.NOCTCODOPE, T1.NOCTTYPOPE, T2.ARCTCODFAM, T2.ARITNATURE, T3.ARKCRITPAR, T3.APKSTDPACK
From NOMENC T1
RIGHT JOIN UARTICLE T3 ON (T1.NOCTCODECP=T3.ARKTCODART AND T1.NOCTCOMCPT=T3.ARKTCOMART)
LEFT JOIN ARTICLE T2 ON (T1.NOCTCODECP=T2.ARKTCODART AND (T1.NOCTCOMCPT=T2.ARCTCODPLA OR T1.NOCTCOMCPT=T2.ARKTCOMART))
WHERE (T1.NOCTCODOPE<>@EMPTY_STRING AND T1.NOCTTYPOPE<>@EMPTY_STRING) AND T2.ARCTCODFAM IN (SELECT CODE FROM @FAMILIAS)
AND T2.ARKTSOC=@GTMEX AND T1.NOKTCODPF=@part_no AND T1.NOKTCOMPF=@line_code;